package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

var (
	rootDir = flag.String("dir", ".", "корневая директория для сканирования")
)

func main() {
	flag.Parse()

	err := filepath.WalkDir(*rootDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			return nil
		}

		// Пропускаем vendor и скрытые директории
		if strings.HasPrefix(d.Name(), ".") || d.Name() == "vendor" {
			return filepath.SkipDir
		}

		return processPackage(path)
	})

	if err != nil {
		fmt.Fprintf(os.Stderr, "ошибка при сканировании: %v\n", err)
		os.Exit(1)
	}
}

func processPackage(dir string) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("не удалось разобрать пакет в %s: %w", dir, err)
	}

	for _, pkg := range pkgs {
		var resetMethods []string

		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				gen, ok := decl.(*ast.GenDecl)
				if !ok || gen.Tok != token.TYPE {
					continue
				}

				for _, spec := range gen.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					// Проверяем, есть ли комментарий // generate:reset
					if gen.Doc == nil {
						continue
					}
					hasReset := false
					for _, comment := range gen.Doc.List {
						if strings.Contains(comment.Text, "generate:reset") {
							hasReset = true
							break
						}
					}
					if !hasReset {
						continue
					}

					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						continue
					}

					methodCode := generateResetMethod(typeSpec.Name.Name, structType, fset)
					resetMethods = append(resetMethods, methodCode)
				}
			}

			// Если нашли структуры с generate:reset — пишем reset.gen.go
			if len(resetMethods) > 0 {
				content := fmt.Sprintf(`// Code generated by reset tool. DO NOT EDIT.
package %s

%s
`, pkg.Name, strings.Join(resetMethods, "\n\n"))

				filename := filepath.Join(dir, "reset.gen.go")
				err := os.WriteFile(filename, []byte(content), 0644)
				if err != nil {
					return fmt.Errorf("не удалось записать файл %s: %w", filename, err)
				}
				fmt.Printf("сгенерировано: %s\n", filename)
			}
		}
	}

	return nil
}

func generateResetMethod(typeName string, structType *ast.StructType, fset *token.FileSet) string {
	var lines []string
	lines = append(lines, fmt.Sprintf("func (rs *%s) Reset() {", typeName))
	lines = append(lines, "    if rs == nil {")
	lines = append(lines, "        return")
	lines = append(lines, "    }")

	for _, field := range structType.Fields.List {
		if len(field.Names) == 0 {
			continue // пропускаем анонимные поля
		}

		fieldName := field.Names[0].Name

		// Получаем строковое представление типа поля
		fieldTypeStr, err := exprToString(field.Type, fset)
		if err != nil {
			continue
		}

		switch {
		case strings.HasPrefix(fieldTypeStr, "[]"): // слайс
			lines = append(lines, fmt.Sprintf("    rs.%s = rs.%s[:0]", fieldName, fieldName))

		case strings.HasPrefix(fieldTypeStr, "map["): // мапа
			lines = append(lines, fmt.Sprintf("    clear(rs.%s)", fieldName))

		case strings.HasPrefix(fieldTypeStr, "*"): // указатель
			baseType := strings.TrimPrefix(fieldTypeStr, "*")
			switch baseType {
			case "string", "int", "bool", "float64", "float32", "int8", "int16", "int32", "int64",
				"uint", "uint8", "uint16", "uint32", "uint64", "byte", "rune":
				lines = append(lines, fmt.Sprintf("    if rs.%s != nil { *rs.%s = %s }", fieldName, fieldName, zeroValue(baseType)))
			default:
				// Для указателей на структуры проверяем, есть ли Reset()
				lines = append(lines, fmt.Sprintf("    if rs.%s != nil { rs.%s.Reset() }", fieldName, fieldName))
			}

		default: // примитивы
			lines = append(lines, fmt.Sprintf("    rs.%s = %s", fieldName, zeroValue(fieldTypeStr)))
		}
	}

	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

// exprToString преобразует AST-узел типа в строку
func exprToString(expr ast.Expr, fset *token.FileSet) (string, error) {
	var buf strings.Builder
	err := printer.Fprint(&buf, fset, expr)
	if err != nil {
		return "", err
	}
	return buf.String(), nil
}

func zeroValue(typeName string) string {
	switch typeName {
	case "string":
		return `""`
	case "bool":
		return "false"
	default:
		return "0" // для числовых типов
	}
}
